export const SUBUSER_LOGIN_REQUEST = "SUBUSER_LOGIN_REQUEST";
export const SUBUSER_LOGIN_SUCCESS = "SUBUSER_LOGIN_SUCCESS";
export const SUBUSER_LOGIN_FAIL = "SUBUSER_LOGIN_FAIL";
export const SUBUSER_LOGOUT = "SUBUSER_LOGOUT";

export const SUBUSER_REGISTER_REQUEST = "SUBUSER_REGISTER_REQUEST";
export const SUBUSER_REGISTER_SUCCESS = "SUBUSER_REGISTER_SUCCESS";
export const SUBUSER_REGISTER_FAIL = "SUBUSER_REGISTER_FAIL";

export const SUBUSER_UPDATE_REQUEST = "SUBUSER_UPDATE_REQUEST";
export const SUBUSER_UPDATE_SUCCESS = "SUBUSER_UPDATE_SUCCESS";
export const SUBUSER_UPDATE_FAIL = "SUBUSER_UPDATE_FAIL";
